import Location from '../../components/homePageComponents/location/Location';
import st from './Contacts.module.scss';
import Link from 'next/link';
export const metadata = {
  title: 'FOX DENTAL | КОНТАКТИ',
  description: 'Generated by create next app',
};

const Contacts = () => {
  return (
    <div className={st.container}>
      <h1 className={st.title}>КОНТАКТИ</h1>
      <div className={st.contacts}>
        <div className={st.hours}>
          <p>пн-пт: 8.00 - 20.00</p>
          <p>сб: 9.00 - 20.00</p>
          <p>нд: вихідний</p>
        </div>

        <div className={st.numbers}>
          <Link href='tel:+380689262855'>
            <h2>+380689262855</h2>
          </Link>
          <Link href='mailto:gmail@gmail.com'>
            <p>gmail@gmail.com</p>
          </Link>
        </div>
      </div>
      <h1 className={st.title}>ЯК ЗНАЙТИ?</h1>
      <div className={st.findUs}>
        <p>
          Клініка знаходиться в центрі міста Вінниці хвилинах пішого ходу від трамвайної зупинки
          «Лікарня Пирогова». У торговому центрі Феріде. В нашому напрямку курсують такі трамваї як
          № 1,4,4,3,3&{' '}
        </p>
      </div>

      <div className={st.location}>
        <h1 className={st.title}>З'ВЯЗАТИСЯ З НАМИ</h1> <Location />
      </div>
    </div>
  );
};

export default Contacts;
