import Location from '../../components/homePageComponents/location/Location';
import st from './Contacts.module.scss';
import Link from 'next/link';
export const metadata = {
  title: 'FOX DENTAL | КОНТАКТИ',
  description: 'Generated by create next app',
};

const Contacts = () => {
  return (
    <div className={st.container}>
      <h1 className={st.title}>КОНТАКТИ</h1>
      <div className={st.contacts}>
        <div className={st.hours}>
          <p>пн-пт: 8.00 - 20.00</p>
          <p>сб: 10.00 - 16.00</p>
          <p>нд: 10.00 - 14.00</p>
        </div>

        <div className={st.numbers}>
          <Link href='tel:380973554125'>
            <h2>+38 (097) 355 41 25</h2>
          </Link>
          <Link href='mailto:gmail@gmail.com'>
            <p>fox-dental@gmail.com</p>
          </Link>
        </div>
      </div>
      <h1 className={st.title}>ЯК ЗНАЙТИ?</h1>
      <div className={st.findUs}>
        <p>
          Клініка знаходиться в самому центрі міста Вінниці, у кількох хвилинах пішого ходу від
          трамвайної зупинки «Лікарня Пирогова». У торговому центрі «Феріде Плаза». В нашому
          напрямку їздить весь громадський транспорт: маршрутне таксі, трамваї, тролейбуси та
          муніципальні автобуси!
        </p>
      </div>

      <div className={st.location}>
        <h1 className={st.title}>З'ВЯЗАТИСЯ З НАМИ</h1> <Location />
      </div>
    </div>
  );
};

export default Contacts;
