import './globals.css';
import { Analytics } from '@vercel/analytics/react';

import Header from '@/components/header/Header';
import Footer from '@/components/footer/Footer';

export const metadata = {
  title: 'FOX DENTAL',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <head>
        <link rel='icon' href='/favicon.svg' />
      </head>
      <body>
        <>
          <Header />
          <Analytics />
          {children}
          <Footer />{' '}
        </>
      </body>
    </html>
  );
}
